services:
  web:
    build: ./web
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=phishuser
      - DB_PASSWORD=DeNeSpart123
      - DB_NAME=phishingdb

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=phishingdb
      - MYSQL_USER=phishuser
      - MYSQL_PASSWORD=DeNeSpart123
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  db_data: